### ISSUE TITLE
OSM attribution on Demo page

### ISSUE THREAD

**Issue by cmonagle** [opennorth/represent-canada#109]
OSM requires attribution when using its tiles.

Looks like we could just plop this around line 135 here https://github.com/opennorth/represent-canada/blob/f35e46ee6945fc8eac6b5a021c59d8ab2adbaa57/finder/static/js/demo.js (Don't have dev env to test)
```
    attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
```

**Comment by jpmckinney** [comment]
Fixed, thanks!
