### ISSUE TITLE
missing download for 'British Columbia municipal councils'

### ISSUE THREAD

**Issue by cmyr** [opennorth/represent-canada#110]
I'm not sure if this file should exist, or if its some parsing error: but there's an item at the bottom of the [downloads page](https://represent.opennorth.ca/data/) for which the link doesn't work.

**Comment by jpmckinney** [comment]
[This is the command that compiles the CSVs](https://github.com/opennorth/scrapers_ca_app/blob/master/reports/management/commands/upload.py), but it hasn't been written to handle the special case of province-wide collections of municipal councils.
