### ISSUE TITLE
new Quebec electoral map

### ISSUE THREAD

**Issue by vwasteels** [opennorth/represent-canada#111]
DGEQ updated its electoral map, 
does the API reflect this change ?

thank you

**Comment by jpmckinney** [comment]
What's the date of the DGEQ update?

**Comment by jpmckinney** [comment]
Also, please provide links to any information from DGEQ about the update.

**Comment by jbbelanger** [comment]
@jpmckinney 
The new map has been adopted in March of last year and will be officielly effective at the start of the electoral campaing (Aug. 28).
https://lacarte.electionsquebec.qc.ca/fr/rapport_final.php
https://www.electionsquebec.qc.ca/francais/provincial/carte-electorale/entites-administratives-liees-a-un-code-postal-2011.php
https://www.electionsquebec.qc.ca/francais/provincial/carte-electorale/geometrie-des-circonscriptions-provinciales-du-quebec.php

**Comment by jpmckinney** [comment]
The boundaries are now available via the API. Thanks for reporting!

http://represent.opennorth.ca/boundary-sets/quebec-electoral-districts-2017/

**Comment by vwasteels** [comment]
thanks for this update,
I'm working on it just now, and it seems there is an issue with the encoding, 
ex:  ```"name": "La Pini\u00c3\u00a8re"```
which gives : ```La PiniÃ¨re```
instead of : ```La Pinière```

Any idea why ?
thanks

**Comment by jpmckinney** [comment]
I'll have a look. Thanks for reporting the issue!

**Comment by jpmckinney** [comment]
I've corrected the encoding issue. For example: http://represent.opennorth.ca/boundaries/quebec-electoral-districts-2017/la-piniere/

Thanks again for reporting!

**Comment by vwasteels** [comment]
thanks !!

BUT ...
(sorry)

I used to rely on this field ```boundaries_concordance```
in this request ```https://represent.opennorth.ca/postcodes/H1W3M1/```
to get the relative provincial district from a post code.

It is empty now, is that normal ?

Is there an alternate way to find a district in a specific ```boundary-sets```, example: ```quebec-electoral-districts-2017``` ?

**Comment by jpmckinney** [comment]
Check `boundaries_centroid`. You should always check both. I don't know if le Directeur général des élections has published a postal code to boundary spreadsheet yet.

**Comment by jpmckinney** [comment]
I just checked – they've updated the file. I'll upload it, and you'll be able to use `boundaries_concordance` again.

**Comment by vwasteels** [comment]
ok thanks !!
