### ISSUE TITLE
Add Yukon boundaries

### ISSUE THREAD

**Issue by jpmckinney** [opennorth/represent-canada#119]
source_url https://open.yukon.ca/data/dataset/yukon-electoral-districts-2008
data_url ftp://ftp.geomaticsyukon.ca/GeoYukon/Administrative_Boundaries/Yukon_Electoral_Districts_2008/Yukon_Electoral_Districts_2008.shp.zip
licence_url https://open.yukon.ca/data/open-government-licence-yukon

**Comment by jpmckinney** [comment]
Now https://map-data.service.yukon.ca/GeoYukon/Administrative_Boundaries/Yukon_Electoral_Districts_2015/

**Comment by elynch303** [comment]
i was looking into this this week we should scrape https://yukonassembly.ca/ just like the other provinces. i also noticed Northwest Territories and Nunavut is missing. and there sites are https://www.ntassembly.ca/ and https://www.assembly.nu.ca/

**Comment by jpmckinney** [comment]
We need the boundaries for NWT and Nunavut. Last time we tried, they wouldn't send the shapefiles.

For Yukon, we just need to add the shapefile above to https://github.com/opennorth/represent-canada-data

**Comment by elynch303** [comment]
so we can not add the members without there boundaries ?

**Comment by jpmckinney** [comment]
It’s possible, but most users interact via the geospatial APIs.

**Comment by jpmckinney** [comment]
Ah, actually we do have the boundaries for NT, so we just need a scraper for representatives, now.

**Comment by jpmckinney** [comment]
Yukon now added.
