### ISSUE TITLE
Missing Members Data Roles

### ISSUE THREAD

**Issue by elynch303** [opennorth/represent-canada#128]
I would like to add some more data endpoints such as the members roles, Committees, Parliamentary Associations and Interparliamentary Groups

roles = string array
```
[
   "Prime Minister",
   "Leader of the Liberal Party"
]
``` 
committees = string array
```
[
   "Special Joint Committee on Medical Assistance in Dying",
   "Subcommittee on Agenda and Procedure of the Special Joint Committee on Medical Assistance in Dying"
]
```
Parliamentary Associations = string array
```
[
"Canada-Europe Parliamentary Association",
"Canadian NATO Parliamentary Association",
"Canadian Branch of the Assemblée parlementaire de la Francophonie",
"Canadian Branch of the Commonwealth Parliamentary Association",
"Canada-United States Inter-Parliamentary Group",
"Canada-United Kingdom Inter-Parliamentary Association",
"Canadian Delegation to the Organization for Security and Co-operation in Europe Parliamentary Assembly",
]
```

this data dose appear to be available for most federal and provincial members as you can see here

https://www.ourcommons.ca/Members/en/ziad-aboultaif(89156)
https://nslegislature.ca/members/profiles/john-white
https://www.ola.org/en/members/all/jill-andrew

**Comment by jpmckinney** [comment]
You can put these additional fields as `extras` on the person in https://github.com/opencivicdata/scrapers-ca

For example: 

https://github.com/opencivicdata/scrapers-ca/blob/42a4433f815282b62161aea9a3a8b6ff575a177f/ca_on/people.py#L59

**Comment by jpmckinney** [comment]
For Canada, you should use the OpenParliament API for committees.

To my knowledge, there are no APIs for the provinces, so they can be modelled as `extras`, though really these things are not properties of a person, but are their own classes.

**Comment by elynch303** [comment]
committees and associations may not be as much a property of a person but i would argue in this case that `roles` make sense have as a top level endpoint similar to `offices`. if we are unable to update the scope at this time then putting them in `extras` would be fine at this time.

**Comment by jpmckinney** [comment]
Yes, let’s use extras.

**Comment by elynch303** [comment]
i will separate the work for roles, committees and associations into separate PR's.

**Comment by jpmckinney** [comment]
Closed by https://github.com/opencivicdata/scrapers-ca/pull/319
